### ISSUE TITLE
EnderIO Redstone & OpenBlocks Fans

### ISSUE THREAD

**Issue by MBfromOK** [OpenMods/OpenBlocks#578]
Minecraft 1.7.10
Forge Mod Loader 7.10.85.1284
Forge 10.13.2.1284
ForgeMultipart-1.7.10-1.1.1.320-universal.jar
EnderIO-1.7.10-2.2.6.317.jar
EnderTech-1.7.10-0.3.0.348.jar
EnderZoo-1.7.10-1.0.5.14.jar
OpenModsLib-1.7.10-0.6-snapshot-225.jar
OpenBlocks-1.7.10-1.3-snapshot-430.jar

I discovered your mod and got all excited to build a waterless mob spawner using your fans with with EnderIO's concealed redstone conduits, I briefly tested it in my test world and thought that it was working, so I started the build... 3 days later I finished the build and flipped the vanilla minecraft switch and nothing happened!

Confused, I exited the game and checked my config file (OpenBlocks.cfg):
>fan {
>    # Maximum force applied every tick to entities nearby (linear decay)
>      D:fanForce=0.05
>
>    # Range of fan in blocks
>    D:fanRange=10.0
>
>    # Is fan force controlled by redstone current
>    B:isRedstoneActivated=true
>}

Yep, everything is good, I go back into my test world and tried every setup I could think of and none of the following work:
![image](https://cloud.githubusercontent.com/assets/7131008/5693956/0519bba4-98fd-11e4-9313-7a19dfc1f477.png)

In fact the only thing that works with my loaded mods is default vanilla minecraft levers, redstone,  & / repeaters.

I am not sure who to report this to so I am posting here first and then will reference this post on their Github.

Also, in the Minecraft Mods List there is an entry that looks wrong, messed up / buggy: 
![image](https://cloud.githubusercontent.com/assets/7131008/5693987/674aa82c-98ff-11e4-86d9-f45f8872e43d.png)

It is followed with:
![image](https://cloud.githubusercontent.com/assets/7131008/5693991/829ef59c-98ff-11e4-81df-996d7f25c696.png)

and:
![image](https://cloud.githubusercontent.com/assets/7131008/5693992/95bb5026-98ff-11e4-895c-50b467429c4d.png)

**Comment by hilburn** [comment]
I had a look at the fan code and the issue seems to be an odd case caused by the fact that conduits (or rednet cables) don't supply redstone to the block they're in, but to the faces they are connected to. Thus your call at https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/tileentity/TileEntityFan.java#L108 to check adjacent blocks indirect power levels returns 0. Checking the Fan's block as well as adjacent ones should fix this.

**Comment by boq** [comment]
Fixed two months ago. Your snapshot it four months old. Do the math and then [download release](openmods.info).

@hilburn We derped and checked only on client side at one point. After fixing that fans work fine with conduits.

**Comment by hilburn** [comment]
ah ok, fair enough

**Comment by MBfromOK** [comment]
@boq Hi, I am an intelligent person, (but not a programmer) who is having a problem.  Your website said to come here to report problems.... I did... 

I can't tell you how frustrating it is to spend my limited free time attempting to avoid terse messages telling me my mod is out of date only to still get the message I tried so hard to avoid... I checked Google and YOUR website for a newer version when things didn't work and I DID update my mod to the most recent version listed on YOUR website... 

I worked a 13 hour day and in the hour or two of "me" time before I went to bed I took the time to  check my mods, update them, test them, and then make not one but *two* posts for the mods related to the issue I am experiencing.
 
Today, I read my e-mail and see that I received the message I was trying so hard to avoid, so I go back to YOUR website and this is what I see (same as yesterday when I spent my valuable time checking for updates and testing before posting):

![image](https://cloud.githubusercontent.com/assets/7131008/5698253/127fd44a-99cf-11e4-90b9-f10466ce1634.png)

Zoomed in:

![image](https://cloud.githubusercontent.com/assets/7131008/5698269/b4844d84-99cf-11e4-9a28-06859e9bffc2.png)

I learned from the another minecraft bug / issue that just because you can find a "newer" version doesn't mean it is the right version so I am trying to stick to official mod author release sites and I don't know how to tell if I should be using "OpenBlocks-1.7.10-1.3-snapshot-543.jar" or "OpenBlocks-1.7.10-1.3-snapshot-430.jar" What I have learned is that generally you want the file that the mod author lists on his / her page (unless it is a forum post that might be out of date) rather than one from some site like minecraftmods.neo.com (made up) and the file on the Official Mod author's webpage is snapshot-430.

You want / say that I should be using a version that isn't 4 months old? Maybe, just maybe you could update (or pass the message to update) the official website with the appropriate "up-to-date" software?!? I don't know what a Jenkins is, how to "compile source", or what Stable vs Snapshot means (other than my best guess). If someone would explain either jenkins or source compiling in a useful way I would be happy to download / test it, but this "Your mod is out of date" thing happened twice in the last 2-3 days and I am livid.

I know you are busy, I appreciate that you have a life and I want you to live it, but please when someone shows they tried have a little heart... I did my homework, please do yours and update your site, if you can't please have someone that can perform the update do it so that people like me can stay up to date easily and enjoy our freetime playing modded Minecraft with great mods like this one.

  I will update because you said to, but please be at least semi professional and update your website.

**Comment by boq** [comment]
Sorry for causing your frustration. Version bugs are common, so I usually just write very short response.

OpenEye, while it's still our project, is not official download site. It's [openmods.info](http://openmods.info) and files posted there ARE official (and recent) release. I tried to include that link in my response, but GitHub interpreted that as link to other repo and made some mess.

Before responding, I used files available on that page and quick test (attaching to side, weak power) confirms that it works. Though I'm not sure what version of EnderIO was used, but I grabbed one of more recent ones from dev/testing server. So I'm little bit puzzled why that didn't work in your case. 

If you have file 'OpenBlocks-1.7.10-1.3.jar` and it doesn't work, it may be renamed snapshot-430 (one used for initial DW20 pack version, so most popular - see [this](http://openeye.openmods.info/file/sha256:9d1d12d81d7e822c4e12aafa8ed6f273fc06ccfdc42a3692b9233f38efc1fdf1)).

openmods.info also contains link to [Jenkins](http://www.openmods.info:8080/) where we have all snapshots - last OpenBlocks build is 543.

Now, while updating, please remember that OpenBlocks and OpenPeripheral both depend on OpenModsLib, so update all three of them simultaneously.

**Comment by MBfromOK** [comment]
Thanks for the reply, I have calmed down after a good nights sleep. :-)

I checked the MANIFEST.MF of the original mod download and found the following:
```
Manifest-Version: 1.0
Jenkins-Build: true
Jenkins-Tag: jenkins-OpenBlocks-529
Jenkins-ID: 2014-12-28_15-01-51
Git-Branch: master
Git-Hash: 8ca8d1a
FMLCorePlugin: openblocks.OpenBlocksCorePlugin
FMLCorePluginContainsFMLMod: true
```

To try and clarify, I went to openmods.info and saw that the filename matched what I had, then clicked the openeye link (just because I was trying to troubleshoot). When I did it gave that massive modlist, I clicked "o" on the index, went down to OpenBlocks (page 5) and clicked it expecting to find a tool that would collect mod usage & crash reports.  That is how I got snapshot 430, which (according to the info in the Manifest.MF  above) the version I originally experienced the issue with was newer than snapshot 430. That is why if would be so great if you would name your download files with the build/version info in the name.

Question: I don't have ComputerCraft  (or OpenPeripheral) installed should I install one or both to help this function better?

**Update:** I have updated to the newest snapshot of OpenBlocks and OpenModsLib available on github The good news is that now the redstone signal is affecting the fans, the problem is that there is still a problem, would you like me to open a new issue or just discuss it here?

**Comment by boq** [comment]
- If this is unrelated problem, then open new discussion. This one is closed.
- Fans were fixed in snapshot 470. Not sure what happened on your instance, but release (i.e. snapshot 529) still works fine
- OpenPeripheral and ComputerCraft are not needed, I just mentioned them just in case you used that
- OpenEye isn't mod download page - links are only bonus feature. Names are unorganized, because we actually operate on hashes. Filenames vary too much from pack to pack and we are only printing first known name for hash for convenience. If you want page that collects downloads, try [this](http://bot.notenoughmods.com/1.7.10.html)
- "American thing"? Bleh, I'm from Europe.
